### ISSUE TITLE
I have an issue help me 

### ISSUE THREAD

**Issue by sienna1022** [kimbo/bluesnarfer#3]
Hi while I try to run ./bluesnarfer -b <mac address> -i on Kali linux WIndow
I got this error ..and I search..I got the answer that I have to configure rfcomm and I try again ./bluesnarfer -b <mac address> -i but I can't solve :(
also I search answers for this error but I can't find them. plz help me
(I'm sorry that my English skill is not good)
![error](https://user-images.githubusercontent.com/81303793/119261103-c2491480-bc10-11eb-9ccd-1aa46c87e60a.PNG)

**Comment by kimbo** [comment]
Questions like this will probably be answered better and receive more attention on stackoverflow.com, so I'm going to close this.

I did see this page which may be of help to you: https://ubuntuforums.org/archive/index.php/t-883847.html

Happy hacking :smile:
